# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-07 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u94fe\u63a5\u540d\u79f0')),
                ('sequence', models.IntegerField(unique=True, verbose_name='\u6392\u5e8f')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('link', models.URLField(verbose_name='\u94fe\u63a5\u5730\u5740')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
